#ifndef AZUSADESIGNERBASE_GLOBAL_H
#define AZUSADESIGNERBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AZUSADESIGNERBASE_LIBRARY)
#  define AZUSADESIGNERBASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define AZUSADESIGNERBASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AZUSADESIGNERBASE_GLOBAL_H
